version: '3.1'

volumes:
  joke_pg_data:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=joke_user
      - POSTGRES_DB=joke_db
    volumes:
      - joke_pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432


